spring:
  application:
    name: discovery-service

eureka:
  instance:
    hostname: localhost
    nonSecurePortEnabled: true
    nonSecurePort: 8002
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/